name: iterate
description: Small helper iteration methods inspired by Ruby
version: 1.0.1
repository: https://github.com/aryehof/dart-iterate

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
